USE BUDT758_DB_0504_06

DROP TABLE Write;
DROP TABLE Belong;
DROP TABLE Restaurant;
DROP TABLE Have;
DROP TABLE Review;
DROP TABLE Shuttle;
DROP TABLE dbo.Stop;
DROP TABLE Category;
DROP TABLE Customer;